name: Testing Prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Run Prisma Migrate
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.PRISMA_DIRECT_URL }}
